### PR TITLE
Update classifiers

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
@dabeaz Hello, any thoughts on this PR? Thanks!

**Comment by dabeaz** [comment]
PLY releases are highly infrequent.  Is there something wrong with simply saying "Python 2" and "Python 3" in the classifiers?

**Comment by hugovk** [comment]
There's nothing wrong with just "Python 2" and "Python 3", but more-granular classifiers give a more accurate picture of what is officially supported, to both humans and programmatically, and the classifiers are a well-known and defined Python convention.

For example, this would clearly show ply supports Python 3.3 but not 3.2.

**Comment by dabeaz** [comment]
PLY releases are rather infrequent and the project is purely in long-term maintenance mode.  I don't want to make a new release just to update the classifiers for every new version of Python.   I'd like to leave it as "Python 2" and "Python 3" generally.

**Pull request closed without merging**
