### PR TITLE
Multithreading fix and simple cleanups

### PR DESCRIPTION
**Pull request by vpelletier**

### CODE REVIEW

**Comment by vpelletier** [comment]
Rebased patch stack over most recent master.
Is there anything wrong in these changes ?

**Comment by vpelletier** [comment]
...and one fix for what looks like a bug.

**Comment by vpelletier** [comment]
Failure seems unrelated to this pull-request:
> $ cd test && python testlex.py && python testyacc.py
> AttributeError: 'module' object has no attribute 'skipUnless'
> The command "cd test && python testlex.py && python testyacc.py" exited with 1.

**Comment by dabeaz** [comment]
Please upgrade to Python 2.7.

**Comment by vpelletier** [comment]
I was quoting TravisCI, actually (I edited the post). Anyway, there is a merge conflict now anyway, so I'll rebase and travis will run again.

**Comment by dabeaz** [comment]
No worries.  That's getting into some pretty obscure magic there---I didn't even remember that PLY would allow that until I read an unrelated bug report about it.

**Comment by dabeaz** [comment]
Partially accepting changes (globals cleanup, extra str(e) conversions, etc.).

**Pull request closed without merging**
