### PR TITLE
Add Python 3.7 and 3.8 to .travis.yml

### PR DESCRIPTION
**Pull request by cclauss**
https://travis-ci.org/dabeaz/ply/pull_requests

### CODE REVIEW

**Comment by cclauss** [comment]
I reverted that change but Travis was shut off a year ago.

**Comment by cclauss** [comment]
Oh... Travis is still running, https://travis-ci.org/dabeaz/ply/pull_requests but the output is no longer linked to the PR.

**Comment by hugovk** [comment]
@dabeaz Hello! I see CI testing was removed in https://github.com/dabeaz/ply/commit/f45aa4e7aadfedbb48142cd8bab18c7cf6622d2e. Is this codebase no longer maintained? Or is there another reason not to use a CI? If you're not a fan of Travis, we could help set up another, for example GitHub Actions. Thanks!

**Comment by dabeaz** [comment]
PLY is a free software project with a single maintainer (myself).   There is a test suite that takes about 3 seconds to run locally on my machine--something that I do before making any kind of commit.  Also, changes are infrequent.      In light of this, and the fact that I'm trying to simplify tooling on my projects, I don't think that having this project integrated with CI is necessary at this time.

**Pull request closed without merging**
